# Form implementation generated from reading ui file 'otaWidget.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OtaWidget(object):
    def setupUi(self, OtaWidget):
        OtaWidget.setObjectName("OtaWidget")
        OtaWidget.resize(649, 500)
        self.gridLayout = QtWidgets.QGridLayout(OtaWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(OtaWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 3, 1, 1)
        self.let_dns = QtWidgets.QLineEdit(OtaWidget)
        self.let_dns.setObjectName("let_dns")
        self.gridLayout.addWidget(self.let_dns, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(OtaWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(OtaWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.pte_serderInfo = QtWidgets.QPlainTextEdit(OtaWidget)
        self.pte_serderInfo.setObjectName("pte_serderInfo")
        self.gridLayout.addWidget(self.pte_serderInfo, 4, 3, 1, 1)
        self.label = QtWidgets.QLabel(OtaWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(OtaWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 2, 1, 1)
        self.let_serverIp = QtWidgets.QLineEdit(OtaWidget)
        self.let_serverIp.setObjectName("let_serverIp")
        self.gridLayout.addWidget(self.let_serverIp, 1, 2, 1, 1)
        self.pte_clientInfo = QtWidgets.QPlainTextEdit(OtaWidget)
        self.pte_clientInfo.setObjectName("pte_clientInfo")
        self.gridLayout.addWidget(self.pte_clientInfo, 4, 2, 1, 1)
        self.pbt_otaFileLoad = QtWidgets.QPushButton(OtaWidget)
        self.pbt_otaFileLoad.setObjectName("pbt_otaFileLoad")
        self.gridLayout.addWidget(self.pbt_otaFileLoad, 2, 3, 1, 1)
        self.let_otaFile = QtWidgets.QLineEdit(OtaWidget)
        self.let_otaFile.setObjectName("let_otaFile")
        self.gridLayout.addWidget(self.let_otaFile, 2, 2, 1, 1)
        self.pbt_dnsSet = QtWidgets.QPushButton(OtaWidget)
        self.pbt_dnsSet.setObjectName("pbt_dnsSet")
        self.gridLayout.addWidget(self.pbt_dnsSet, 1, 3, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(OtaWidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 6, 0, 1, 4)

        self.retranslateUi(OtaWidget)
        QtCore.QMetaObject.connectSlotsByName(OtaWidget)

    def retranslateUi(self, OtaWidget):
        _translate = QtCore.QCoreApplication.translate
        OtaWidget.setWindowTitle(_translate("OtaWidget", "Form"))
        self.label_4.setText(_translate("OtaWidget", "服务器回复"))
        self.label_2.setText(_translate("OtaWidget", "ota文件"))
        self.label_5.setText(_translate("OtaWidget", "服务器ip"))
        self.label.setText(_translate("OtaWidget", "域名"))
        self.label_3.setText(_translate("OtaWidget", "客户端请求信息"))
        self.pbt_otaFileLoad.setText(_translate("OtaWidget", "load"))
        self.pbt_dnsSet.setText(_translate("OtaWidget", "生效"))
