# Form implementation generated from reading ui file 'findStringAsk.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_search(object):
    def setupUi(self, search):
        search.setObjectName("search")
        search.resize(397, 133)
        search.setMinimumSize(QtCore.QSize(397, 133))
        search.setMaximumSize(QtCore.QSize(397, 133))
        self.gridLayout = QtWidgets.QGridLayout(search)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_findStr = QtWidgets.QLineEdit(search)
        self.lineEdit_findStr.setObjectName("lineEdit_findStr")
        self.gridLayout.addWidget(self.lineEdit_findStr, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(search)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.upOrLowBox = QtWidgets.QCheckBox(search)
        self.upOrLowBox.setObjectName("upOrLowBox")
        self.gridLayout.addWidget(self.upOrLowBox, 3, 0, 1, 1)
        self.find = QtWidgets.QPushButton(search)
        self.find.setObjectName("find")
        self.gridLayout.addWidget(self.find, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(search)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(search)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.forward = QtWidgets.QRadioButton(self.groupBox)
        self.forward.setObjectName("forward")
        self.horizontalLayout.addWidget(self.forward)
        self.backForward = QtWidgets.QRadioButton(self.groupBox)
        self.backForward.setObjectName("backForward")
        self.horizontalLayout.addWidget(self.backForward)
        self.gridLayout.addWidget(self.groupBox, 3, 1, 1, 1)
        self.next = QtWidgets.QPushButton(search)
        self.next.setObjectName("next")
        self.gridLayout.addWidget(self.next, 1, 2, 1, 1)
        self.lineEdit_replace = QtWidgets.QLineEdit(search)
        self.lineEdit_replace.setObjectName("lineEdit_replace")
        self.gridLayout.addWidget(self.lineEdit_replace, 1, 1, 1, 1)
        self.replace = QtWidgets.QPushButton(search)
        self.replace.setObjectName("replace")
        self.gridLayout.addWidget(self.replace, 0, 3, 1, 1)
        self.cancel = QtWidgets.QPushButton(search)
        self.cancel.setObjectName("cancel")
        self.gridLayout.addWidget(self.cancel, 3, 3, 1, 1)
        self.replaceAll = QtWidgets.QPushButton(search)
        self.replaceAll.setObjectName("replaceAll")
        self.gridLayout.addWidget(self.replaceAll, 1, 3, 1, 1)

        self.retranslateUi(search)
        QtCore.QMetaObject.connectSlotsByName(search)

    def retranslateUi(self, search):
        _translate = QtCore.QCoreApplication.translate
        search.setWindowTitle(_translate("search", "查找"))
        self.label_2.setText(_translate("search", "替代内容"))
        self.upOrLowBox.setText(_translate("search", "大小敏感"))
        self.find.setText(_translate("search", "find"))
        self.label.setText(_translate("search", "查找内容"))
        self.groupBox.setTitle(_translate("search", "查找方向"))
        self.forward.setText(_translate("search", "向前"))
        self.backForward.setText(_translate("search", "向后"))
        self.next.setText(_translate("search", "next"))
        self.replace.setText(_translate("search", "替换"))
        self.cancel.setText(_translate("search", "取消"))
        self.replaceAll.setText(_translate("search", "替换所有"))
