# Form implementation generated from reading ui file 'Ui_BleMainWin.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BleMainWin(object):
    def setupUi(self, BleMainWin):
        BleMainWin.setObjectName("BleMainWin")
        BleMainWin.resize(800, 600)
        BleMainWin.setWindowTitle("")
        self.centralwidget = QtWidgets.QWidget(BleMainWin)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        BleMainWin.setCentralWidget(self.centralwidget)

        self.retranslateUi(BleMainWin)
        QtCore.QMetaObject.connectSlotsByName(BleMainWin)

    def retranslateUi(self, BleMainWin):
        pass
